### ISSUE TITLE
Please use `https://github.com/` in package.json, instead of `github:`

### ISSUE THREAD

**Issue by catscarlet** [savetheclocktower/pulsar-ide-typescript-alpha#1]
One dependency
```
"atom-languageclient": "github:savetheclocktower/atom-languageclient"
```
is using `git+ssh://git@github.com/savetheclocktower/atom-languageclient.git`, which is not supported by GitHub anymore. The unauthenticated git protocol on port 9418 is no longer supported. This cause the package unable to install.

Related info:
- https://stackoverflow.com/questions/70663523/the-unauthenticated-git-protocol-on-port-9418-is-no-longer-supported
- https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git

**Comment by savetheclocktower** [comment]
Changed to a published NPM dependency a while back, so I'm closing this. Thanks!
